compile operation now works with include directive
turned out to be a lot more straightforward than I thought

diff --git a/bin/bork-compile b/bin/bork-compile
--- a/bin/bork-compile
+++ b/bin/bork-compile
@@ -41,6 +41,29 @@ strip_blanks () {
   awk '!/^($|[[:space:]]*#)/{print $0}' <&0
 }
 
+compile_file () {
+    cat $1 | while read line; do
+        first_token=$(str_get_field "$line" 1)
+        case $first_token in
+            ok)
+                type=$(str_get_field "$line" 2)
+                fn=$(_lookup_type $type)
+                if [ -z "$fn" ]; then
+                    echo "type $type not found, can't proceed" 1>&2
+                    exit 1
+                fi
+                include_assertion $type $fn
+                compile_cmd=$(echo "$line" | sed -E "s|ok $type ||")
+                . $fn compile $compile_cmd
+                echo "$line"
+                ;;
+            register|include) eval "$line" ;;
+            *) echo "$line" ;;
+        esac
+    done
+}
+
+
 cat <<DONE
 #!/usr/bin/env bash
 $setupFn
@@ -78,27 +101,4 @@ if [ -n "$conflicts" ]; then
   esac
 fi
 
-cat $config | while read line; do
-  first_token=$(str_get_field "$line" 1)
-  case $first_token in
-    ok)
-      type=$(str_get_field "$line" 2)
-      fn=$(_lookup_type $type)
-      if [ -z "$fn" ]; then
-        echo "type $type not found, can't proceed" 1>&2
-        exit 1
-      fi
-      include_assertion $type $fn
-      compile_cmd=$(echo "$line" | sed -E "s|ok $type ||")
-      . $fn compile $compile_cmd
-      echo "$line"
-      ;;
-    register) eval "$line" ;;
-    include)
-      echo "include not supported for 'compile' operation yet" 1>&2
-      exit 1
-      ;;
-    *) echo "$line" ;;
-  esac
-done
-
+compile_file $config
